services:
    web:
        profiles: [web]
        restart: unless-stopped
        image: registry.mr.pk-8.ru/veneridze/laravel-octane:8.4
        command: "/usr/bin/php84 /app/wiki/artisan octane:start --server=roadrunner --rpc-port=6001 --host=0.0.0.0 --port=80 --workers=20"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "/usr/bin/php84 /app/wiki/artisan octane:status --no-ansi | grep -q 'Octane server is running' && exit 0 || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        labels:
            traefik.enable: true
            traefik.http.routers.wiki.rule: HostRegexp(`wiki\..[a-z-]\.pk-8\.ru`)
            traefik.http.routers.wiki.entrypoints: websecure
            traefik.http.services.wiki.loadbalancer.server.port: 80
        volumes:
            - ".:/app/wiki"
        networks:
            app:
            web: 
                aliases:
                    - wiki_web
            database:
    queue:
        profiles: [backend, queue]
        restart: unless-stopped
        image: registry.mr.pk-8.ru/veneridze/laravel-octane:8.4
        command:
            [
                "/bin/bash",
                "-c",
                "cd /app/wiki && /usr/bin/php84 -d variables_order=EGPCS artisan queue:listen",
            ]
        # network_mode: "service:web"
        volumes:
            - ".:/app/wiki"
        networks:
            - app
            - database
    schedule:
        profiles: [backend, schedule]
        restart: unless-stopped
        image: registry.mr.pk-8.ru/veneridze/laravel-octane:8.4
        # network_mode: "service:web"
        command:
            [
                "/bin/bash",
                "-c",
                "cd /app/wiki && /usr/bin/php84 -d variables_order=EGPCS artisan schedule:work",
            ]
        volumes:
            - ".:/app/wiki"
        networks:
            - app
            - database
    redis:
        profiles: [web, backend, redis]
        image: registry.mr.pk-8.ru/library/redis:alpine
        restart: unless-stopped
        command: redis-server --appendonly yes --protected-mode no
        volumes:
            - ./redis:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            app:
                aliases:
                    - redis
networks:
    web:
        external: true
    database:
        external: true
    app:
        driver: bridge
